name: discovery
channels:
  - https://nexus_eut_svc:AKCp8hzCxcyh1Uh9s4LMNZKmEHY1V4jwUhfqRsEUvdvMNZKhyncwt8MTtzwaq2rZkhx6dxW3e@ndartifactory.jfrog.io/artifactory/api/conda/conda
  - https://nexus_eut_svc:AKCp8hzCxcyh1Uh9s4LMNZKmEHY1V4jwUhfqRsEUvdvMNZKhyncwt8MTtzwaq2rZkhx6dxW3e@ndartifactory.jfrog.io/artifactory/api/conda/conda-forge
dependencies:
  - python==3.7.6
  - pandas
  - gensim
  - pattern
  - umap-learn
  - hdbscan
  - wordcloud
  - tensorflow
  - tensorflow-hub
  - pytorch
  - pytorch_scatter
  - sentence-transformers
  - hnswlib
  - ipykernel
  - nd_nexus_data_access
  - pyodbc
  - nbformat
  - pyyaml
  - nbconvert=5.6.1
  - jupyter
  - jupyter_client
  - s3contents
  - nbformat
  - notebook
  - black
  - nbqa
  - pylint
  - pytest
  - pytest-cov
  - isort
  - cython
  - nteract-scrapbook
  - pigar
  - pipreqs
  - networkx
