name: sciflow
dependencies:
  - python==3.7.6
  - nbdev
  - fastcore
  - pandas
  - ipykernel
  - turbodbc
  - pyodbc
  - boto3
  - s3fs=0.5.1
  - fsspec=0.8.3
  - nbformat
  - pyyaml
  - nbconvert=5.6.1
  - jupyter
  - jupyter_client
  - papermill
  - notebook
  - black
  - nbqa=0.6.1
  - pylint
  - isort
  - autoflake
  - pre_commit
  - mamba
  - boa
  - conda-verify
  - numba
  - cython
  - pigar
  - twine
  - networkx
  - graphviz
  - pyrsistent
  - dvc
  - metaflow
  - sagemaker
  - tinydb
  - pip
  - pip:
      - sacred
