package:
  name: sciflow
  version: 0.0.1
requirements:
  host:
  - pip
  - python
  - setuptools
  run:
  - PyYAML==5.4.1
  - boto3==1.17.46
  - botocore==1.20.106
  - fastcore==1.3.26
  - incense==0.0.11
  - nbdev==1.1.20
  - nbformat==5.1.3
  - nbqa==0.6.1
  - networkx==2.6.2
  - numpy==1.20.1
  - pandas==1.2.4
  - pyodbc==4.0.31
  - pyrsistent==0.17.3
  - sacred==0.8.2
  - tinydb==4.4.0
source:
  path: /home/jovyan/git/sciflow
