package:
  name: scidev
  version: "0.0.1"

build:
  number: 0
  
source:
  path: ../scidev
  
requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - numpy==1.19.2 
    - nbformat==5.0.8
    - nbqa==0.5.6
    - nbdev==1.1.12
    - fastcore==1.3.19