# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"extract_named_export": "export_named.ipynb",
         "is_export_extended": "export_named.ipynb",
         "set_orig_value": "export_named.ipynb",
         "sciflow_build_lib": "export_named.ipynb",
         "run_nbqa_cmd": "nb_lint.ipynb",
         "sciflow_tidy": "nb_lint.ipynb",
         "determine_dependencies": "packaging.ipynb",
         "find_params_cell": "params.ipynb",
         "DEFAULT_PARAMS_CELL": "params.ipynb",
         "add_missing_params_cell": "params.ipynb",
         "extract_params_to_file": "params.ipynb",
         "list_mod_files": "params.ipynb",
         "extract_as_files": "params.ipynb",
         "extract_params_as_dict": "params.ipynb",
         "extract_step_code": "parse_module.ipynb",
         "parse_step": "parse_module.ipynb",
         "extract_steps": "parse_module.ipynb",
         "extract_dag": "parse_module.ipynb",
         "first": "test_export.ipynb",
         "function": "test_export.ipynb",
         "created_new_module": "test_export.ipynb",
         "internal": "test_export.ipynb",
         "preprocess": "test_export.ipynb",
         "source_in_docs": "test_export.ipynb",
         "train": "test_export.ipynb",
         "last": "test_export.ipynb"}

modules = ["export_named.py",
           "nb_lint.py",
           "packaging.py",
           "params.py",
           "parse_module.py",
           "test_export.py",
           "test_module.py"]

doc_url = "https://{user}.github.io/sciflow/"

git_url = "https://github.com/{user}/sciflow/tree/{branch}/"

def custom_doc_links(name): return None
