# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/export_named.ipynb (unless otherwise specified).

__all__ = []

# Cell

# some line comment
import os
import re
from pathlib import Path

from nbdev.export import *
from nbdev.export import Config, _deal_import, _from_future_import, _add2all
from nbformat import NotebookNode
import nbformat
import nbdev