# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/init.ipynb (unless otherwise specified).

__all__ = ['sciflow_init']

# Cell

from pathlib import Path

from fastcore.script import Param, call_parse

# Cell


@call_parse
def sciflow_init(project_root: Param("The root directory of the project", Path) = None):
    pass
    # Add project_root to PYTHONPATH
    # Copy template files to project root
    # Create sciflow env file if it doesn't exist