# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/params.ipynb.

# %% auto 0
__all__ = ['DEFAULT_PARAMS_CELL', 'find_params_cell', 'extract_params', 'add_missing_params_cell', 'extract_params_to_file',
           'list_mod_files', 'extract_as_files', 'extract_params_as_dict', 'params_as_dict']

# %% ../nbs/params.ipynb 2
# | export

import os
from io import StringIO
from pathlib import Path
from typing import Iterable

import nbformat
from execnb.nbio import read_nb
from nbdev.config import get_config
from nbdev.doclinks import nbglob
from nbformat.notebooknode import NotebookNode

# %% ../nbs/params.ipynb 4
# | export


def find_params_cell(nb: NotebookNode):
    params_cell = [c for c in nb["cells"] if c["metadata"] == {"tags": ["parameters"]}]
    return params_cell

# %% ../nbs/params.ipynb 7
# | export


def extract_params(nb: NotebookNode):
    params_cell = find_params_cell(nb)
    return params_cell[0]["source"] if len(params_cell) > 0 else None

# %% ../nbs/params.ipynb 9
# | export

DEFAULT_PARAMS_CELL = {
    "cell_type": "code",
    "execution_count": None,
    "metadata": {"tags": ["parameters"]},
    "outputs": [],
    "source": "# parameters\n",
}

# %% ../nbs/params.ipynb 10
# | export


def add_missing_params_cell(nb_path: Path, persist: bool = True):
    nb = read_nb(nb_path)
    if len(find_params_cell(nb)) > 0:
        print(f"Skipping {nb_path} already has parameters cell")
        return
    nb["cells"].insert(0, nbformat.from_dict(DEFAULT_PARAMS_CELL))
    if persist:
        nbformat.write(nb, nb_path)
    return nb

# %% ../nbs/params.ipynb 12
# | export


def extract_params_to_file(nb_path: Path, params_file_path: Path):
    params_code = extract_params(read_nb(Path(test_nb)))
    with open(params_file_path, "w") as params_file:
        params_file.writelines(params_code)

# %% ../nbs/params.ipynb 14
# | export


def list_mod_files(files):
    modules = []
    for f in files:
        fname = Path(f)
        nb = read_nb(fname)
        default = find_default_export(nb["cells"])
        if default is not None:
            default = os.path.sep.join(default.split("."))
            modules.append(default)
    return modules

# %% ../nbs/params.ipynb 15
# | export


def extract_as_files(suffix="_params.py"):
    nbs = nbglob(recursive=True)
    param_files = list_mod_files(nbs)
    params_files = [
        Path(os.path.join(get_config().path("lib_path"), pf + suffix))
        for pf in param_files
    ]
    for nb_path, pf_path in zip(nbs, params_files):
        extract_params_to_file(nb_path, pf_path)

# %% ../nbs/params.ipynb 16
# | exporti


def _lines_to_dict(lines: Iterable[str]):
    result = {}
    for line in lines:
        if line.startswith("#") or not "=" in line:
            continue
        (key, val) = line.split("=")
        result[key.strip()] = val.strip('\n "')
    return result

# %% ../nbs/params.ipynb 17
# | export


def extract_params_as_dict(params_file_path: Path):
    params = {}
    with open(params_file_path, "r") as params_file:
        params = _lines_to_dict(params_file.readlines())
    return params

# %% ../nbs/params.ipynb 19
# | export


def params_as_dict(nb_path: Path):
    params_code = extract_params(read_nb(nb_path))
    params = _lines_to_dict(StringIO(params_code).readlines())
    return params
