# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/test_ratio.ipynb (unless otherwise specified).

__all__ = ['Topics', 'hierarchical_topic_reduction', 'class_test_code']

# Cell
class_test_code = """
# export


class Topics:
    def __init__(self, documents, workers, speed):
        pass

    def get_num_topics(self):
        return 6

    def get_topic_sizes(self):
        return [1, 2, 3, 4, 5, 6], [1, 2, 3, 4, 5, 6]

    def get_topics(self, num_topics):
        return (
            ["cat", "sat", "mat", "mouse", "house", "grouse"],
            np.asarray([1, 1, 1, 1, 1, 1]),
            [1, 2, 3, 4, 5, 6],
        )

    def search_documents_by_topic(self, topic_num, num_docs):
        return (
            ["cat", "sat", "mat", "mouse", "house", "grouse"],
            np.asarray([1, 1, 1, 1, 1, 1]),
            [1, 2, 3, 4, 5, 6],
        )

    def generate_topic_wordcloud(self, topic_num):
        print("wordcloud")

def hierarchical_topic_reduction(num_topics):
    return ["cat", "sat", "mat"]

hierarchical_topic_reduction(7)
"""