# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/test_ratio.ipynb (unless otherwise specified).

__all__ = ['something', 'nb_cell_code']

# Cell

from collections import Counter
import ast
import nbformat

from nbdev.export import read_nb
from .utils import load_nb_module

# Cell
nb_cell_code = """
def something():
    pass; pass
#load_ext autoreload
#autoreload 2
# export


import numpy as np
import pandas as pd
from .utils import lib_path, odbc_connect, query
pd.set_option("display.max_colwidth", 800)
# export
"""