# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/test/test_export.ipynb (unless otherwise specified).

__all__ = ['first', 'function', 'source_in_docs', 'train', 'last']

# step:first
# irrelevant comment
from typing import List

def first(some_params: List[str]):
    print(''.join(some_params))
    return len(some_params)

# Cell
# some other comment
def function():
    return 1

# Internal Cell

internal = True

# Cell

source_in_docs = True

# Cell
import time
time.sleep(1)

# Cell

#export
import time
time.sleep(3)

# step:train
import time
def train(input_path: Path, model_path: Path):
    import pandas as pd
    print(f'Training {model_path} on {input_path}...')
    time.sleep(1)

# step:last
# TODO: finisih this
def last(some_param: None):
    return 1