# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/test/test_module.ipynb (unless otherwise specified).

__all__ = ['created_new_module', 'first', 'source_in_docs']

# Comes from test_export.ipynb, cell

created_new_module =True

# step:first
from typing import List

def first(some_params: List[str]):
    print(''.join(some_params))
    return len(some_params)

# Internal Cell

internal = True

# Cell

source_in_docs = True