# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/test/test_module.ipynb.

# %% auto 0
__all__ = ['some_param', 'source_in_docs', 'first']

# %% ../../nbs/test/test_module.ipynb 2
# | export

some_param = 2

# %% ../../nbs/test/test_module.ipynb 3
# | export_step first


def first(some_param: int):
    print(some_param)
    another_int = some_param + 5
    results = {"another_int": another_int}
    return results

# %% ../../nbs/test/test_module.ipynb 5
# | exporti


internal = True

# %% ../../nbs/test/test_module.ipynb 6
# | exports

source_in_docs = True
