# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/test/test_module.ipynb (unless otherwise specified).

__all__ = ['created_new_module', 'some_param', 'first', 'source_in_docs', 'created_new_module']

# Comes from test_export.ipynb, cell

created_new_module = True

# Cell

some_param = 2

# step:first


def first(some_param: int):
    print(some_param)
    return some_param

# Internal Cell

internal = True

# Cell

source_in_docs = True

# Comes from test_pandas_numpy.ipynb, cell

created_new_module = True