# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/test/test_module.ipynb (unless otherwise specified).

__all__ = ['created_new_module', 'some_param', 'first', 'source_in_docs']

# Comes from test_export.ipynb, cell

created_new_module = True

# Cell

some_param = 2

# step:first


def first(some_param: int, tracker):
    print(some_param)
    another_int = some_param + 5
    results = {"another_int": another_int}
    return results

# Internal Cell

internal = True

# Cell

source_in_docs = True