# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/test/test_multistep_no_params.ipynb.

# %% auto 0
__all__ = ['traffic_percent', 'workers', 'model_level', 'min_date', 'something', 'get_traffic_text', 'get_experiment_segment',
           'get_utterances', 'preprocess', 'Topics', 'fit', 'evaluate', 'serve_num_topics']

# %% ../../nbs/test/test_multistep_no_params.ipynb 2
# | export_step first


def something():
    print("The first step")

# %% ../../nbs/test/test_multistep_no_params.ipynb 5
# | export


import numpy as np
import pandas as pd

from ..utils import lib_path

# %% ../../nbs/test/test_multistep_no_params.ipynb 7
# | export

traffic_percent = 1
workers = 8
model_level = "dispatcher"
min_date = "2021-01-01"

# %% ../../nbs/test/test_multistep_no_params.ipynb 8
# | export


def get_traffic_text(percent):
    return str(percent) if int(percent) >= 10 else "0" + str(percent)

# %% ../../nbs/test/test_multistep_no_params.ipynb 12
# | export


def get_experiment_segment(traffic_percent):
    return tuple(get_traffic_text(tp) for tp in range(traffic_percent))

# %% ../../nbs/test/test_multistep_no_params.ipynb 14
# | export


def get_utterances(model_level=None, min_date=None, traffic_percent=100):
    """
    You will probably call data preparation code here. To simplify dependencies we are just creating synthetic data instead.
    """
    get_experiment_segment(traffic_percent)
    dummy_data = pd.Series(
        np.random.choice(
            [
                "Hello",
                "Goodbye",
                "Hi",
                "Can you help?",
                "I have an issue, can you help me?",
            ],
            100,
        ),
        name="utterance",
    )
    return dummy_data

# %% ../../nbs/test/test_multistep_no_params.ipynb 15
# | export_step preprocess


def preprocess(model_level=None, min_date=None, traffic_percent=100):
    data = get_utterances(model_level, min_date, traffic_percent)
    documents = data.tolist()
    results = {"documents": documents}
    return results

# %% ../../nbs/test/test_multistep_no_params.ipynb 18
# | export


class Topics:
    def __init__(self, documents, workers):
        pass

    def get_num_topics(self):
        return 6

    def get_topic_sizes(self):
        return [1, 2, 3, 4, 5, 6], [1, 2, 3, 4, 5, 6]

    def get_topics(self, num_topics):
        return (
            ["cat", "sat", "mat", "mouse", "house", "grouse"],
            np.asarray([1, 1, 1, 1, 1, 1]),
            [1, 2, 3, 4, 5, 6],
        )

    def plot_wordcloud(self):
        print("you may want to remove plotting code from testing to speed things up")

# %% ../../nbs/test/test_multistep_no_params.ipynb 20
# | export_step fit


def fit(documents, workers=workers):
    model = Topics(documents, workers=float(workers) * 2)
    training_artifact = {"some": np.arange(10**3)}
    results = {"model": model, "training_artifact": training_artifact}
    return results

# %% ../../nbs/test/test_multistep_no_params.ipynb 32
# | export_step evaluate


def evaluate(documents, model, training_artifact):
    docs_len = len(documents)
    artifact_len = training_artifact["some"].shape[0]
    topic_words, word_scores, topic_nums = model.get_topics(model.get_num_topics())

    topic_contains_non_empty_words = all([len(tw) > 0 for tw in topic_words])
    word_scores_in_range = word_scores.min() >= 0.0 and word_scores.max() <= 1.0
    as_many_items_as_topics = (
        model.get_num_topics() == len(topic_words) == word_scores.shape[0]
    )
    word_summaries = (
        topic_contains_non_empty_words
        and word_scores_in_range
        and as_many_items_as_topics
    )
    # You can add artifacts in a step that will be saved to block storage. Add the paths to the file on the local filesystem
    # and the artifact will be uploaded to remote storage.
    sample_df = pd.DataFrame(
        {"a": model.get_topic_sizes()[0], "b": model.get_topic_sizes()[1]}
    )
    sample_df.to_csv("/tmp/dataframe_artifact.csv", index=False)
    artifacts = ["/tmp/dataframe_artifact.csv"]
    # You can add step metrics too this time just add a list of 3-tuples where tuple order = (name, value, step)
    metrics = [("mae", 100, 0), ("mae", 67, 1), ("mae", 32, 2)]
    results = {
        "word_summaries": word_summaries,
        "artifacts": artifacts,
        "metrics": metrics,
    }
    return results

# %% ../../nbs/test/test_multistep_no_params.ipynb 35
# | export


def serve_num_topics(model):
    return model.get_num_topics()
