# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"generate_msg": "01_hello_nbdev.ipynb",
         "first": "02_hello_sciflow.ipynb",
         "traffic_percent": "04_notebook_quality.ipynb",
         "second": "02_hello_sciflow.ipynb",
         "workers": "04_notebook_quality.ipynb",
         "model_level": "04_notebook_quality.ipynb",
         "min_date": "04_notebook_quality.ipynb",
         "some_func": "04_notebook_quality.ipynb",
         "get_traffic_text": "04_notebook_quality.ipynb"}

modules = ["hello_nbdev.py",
           "hello_sciflow.py",
           "tidying_notebooks.py"]

doc_url = "https://newdaytechnology.github.io/sciflow_examples/"

git_url = "https://github.com/newdaytechnology/sciflow/tree/{branch}/"

def custom_doc_links(name): return None
