# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"something": "complete_workflow.ipynb",
         "traffic_percent": "hello_sciflow.ipynb",
         "workers": "complete_workflow.ipynb",
         "model_level": "complete_workflow.ipynb",
         "min_date": "complete_workflow.ipynb",
         "get_traffic_text": "complete_workflow.ipynb",
         "get_experiment_segment": "complete_workflow.ipynb",
         "get_utterances": "complete_workflow.ipynb",
         "preprocess": "complete_workflow.ipynb",
         "Topics": "complete_workflow.ipynb",
         "fit": "complete_workflow.ipynb",
         "evaluate": "complete_workflow.ipynb",
         "serve_num_topics": "complete_workflow.ipynb",
         "first": "hello_sciflow.ipynb",
         "second": "hello_sciflow.ipynb"}

modules = ["cleaning_notebooks.py",
           "test/test_clustering.py",
           "hello_sciflow.py"]

doc_url = "https://newdaytechnology.github.io/sciflow/"

git_url = "https://github.com/newdaytechnology/sciflow/tree/{branch}/"

def custom_doc_links(name): return None
