# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"generate_msg": "01_hello_nbdev.ipynb",
         "first": "02_hello_sciflow.ipynb",
         "traffic_percent": "tidying_notebooks.ipynb",
         "second": "02_hello_sciflow.ipynb",
         "something": "complete_workflow.ipynb",
         "workers": "tidying_notebooks.ipynb",
         "model_level": "tidying_notebooks.ipynb",
         "min_date": "tidying_notebooks.ipynb",
         "get_traffic_text": "tidying_notebooks.ipynb",
         "get_experiment_segment": "complete_workflow.ipynb",
         "get_utterances": "complete_workflow.ipynb",
         "preprocess": "complete_workflow.ipynb",
         "Topics": "complete_workflow.ipynb",
         "fit": "complete_workflow.ipynb",
         "evaluate": "complete_workflow.ipynb",
         "serve_num_topics": "complete_workflow.ipynb",
         "some_func": "tidying_notebooks.ipynb"}

modules = ["hello_nbdev.py",
           "hello_sciflow.py",
           "test/test_clustering.py",
           "tidying_notebooks.py"]

doc_url = "https://newdaytechnology.github.io/sciflow/"

git_url = "https://github.com/newdaytechnology/sciflow/tree/{branch}/"

def custom_doc_links(name): return None
