# AUTOGENERATED! DO NOT EDIT! File to edit: cleaning_notebooks.ipynb (unless otherwise specified).

__all__ = ['something', 'traffic_percent', 'workers', 'model_level', 'min_date', 'get_traffic_text']

# step:first


def something():
    print("The first step")

# Cell


import numpy as np
import pandas as pd
from sciflow.utils import lib_path

# Cell

traffic_percent = 1
workers = 8
model_level = "dispatcher"
min_date = "2021-01-01"

# Cell


def get_traffic_text(percent):
    return str(percent) if int(percent) >= 10 else "0" + str(percent)