# AUTOGENERATED! DO NOT EDIT! File to edit: 02_hello_sciflow.ipynb (unless otherwise specified).

__all__ = ['first', 'traffic_percent', 'second', 'third']

# Cell

from pathlib import Path

from sciflow.run_flow import check_call_flow, run_flow_async
from sciflow.to_metaflow import sciflow_metaflow

# step:first


def first():
    print("The first step")

# Cell


# Cell

traffic_percent = 1

# step:second


def second(traffic_percent):
    results = {}
    print(f"Traffic percent: {traffic_percent}")
    results["traffic_multiplied"] = traffic_percent * 2
    return results

# step:third


def third(traffic_percent):
    print(f"Traffic * 3={traffic_percent * 3}")