# AUTOGENERATED! DO NOT EDIT! File to edit: 01_hello_nbdev.ipynb (unless otherwise specified).

__all__ = ['generate_msg']

# Cell

import os
from pathlib import Path

from nbdev.export import notebook2script, get_config
from nbdev.test import test_nb, _test_one

# Cell

def generate_msg(msg):
    return f"Hello nbdev: {msg}"