# AUTOGENERATED! DO NOT EDIT! File to edit: 04_notebook_quality.ipynb (unless otherwise specified).

__all__ = ['traffic_percent', 'workers', 'model_level', 'min_date', 'some_func', 'get_traffic_text']

# Cell

import os
from typing import Tuple

# Cell

traffic_percent = 1
workers = 8
model_level = "dispatcher"
min_date = "2021-01-01"

# Cell


def some_func(param: Tuple[int, int]) -> int:
    return param[0] + param[1]

# Cell


def get_traffic_text(percent):
    return (
        str(percent)
        if int(percent) >= 10
        else "0"
        + str(percent)
        + str(percent)
        + str(percent)
        + str(percent)
        + str(percent)
        + str(percent)
        + str(percent)
        + f"some other long text {434234234324}"
    )